import mongoose, {Schema, Document} from "mongoose"

// Quiz:
interface IAnswer extends Document {
    _id: string, // Unique ID auto-generated by DB
    content: string
}

interface IQuizItem extends Document {
    _id: string, // Unique ID auto-generated by DB
    question: string,
    answers: IAnswer[],
    correctAnswerContent: string
}

interface IQuiz extends Document {
    _id: string, // Unique ID auto-generated by DB
    ownerId: string,
    name: string, // Quiz name
    quizItems: IQuizItem[], // Questions/Answers
    image: string, // Image URL
    description: string
}

const answerSchema = new Schema<IAnswer>({
    content: {
        type: String,
        required: true
    }
})

const quizItemSchema = new Schema<IQuizItem>({
    question: {
        type: String,
        required: true
    },
    answers: {
        type: [answerSchema],
        required: true
    },
    correctAnswerContent: { // Used content instead of id
        type: String,
        required: true
    }
})

const quizSchema = new Schema<IQuiz>({
    ownerId: {
        type: String,
        required: true
    },
    name: {
        type: String,
        required: true
    },
    quizItems: {
        type: [quizItemSchema],
        required: true
    },
    image: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    }
})

// User:
interface IUser extends Document {
    // Unique ID auto-generated by DB
    email: string,
    password: string,
    // Additional attributes as needed...
}

const userSchema = new Schema<IUser>({
    email: {
        type: String,
        required: true,
        unique: true // Prevent duplicate emails
    },
    password: {
        type: String,
        required: true
    }
})

// Clear the cache before defining models (prevents issue if code changes)
if (mongoose.models) {
    if (mongoose.models.Answer) delete mongoose.models.Answer
    if (mongoose.models.QuizItem) delete mongoose.models.QuizItem
    if (mongoose.models.Quiz) delete mongoose.models.Quiz
    if (mongoose.models.User) delete mongoose.models.User
}

// Construct the models and export them
const Answer = mongoose.models.Answer || mongoose.model("Answer", answerSchema)
const QuizItem = mongoose.models.QuizItem || mongoose.model("QuizItem", quizItemSchema)
const Quiz = mongoose.models.Quiz || mongoose.model("Quiz", quizSchema)
const User = mongoose.models.User || mongoose.model("User", userSchema)
export {User, Answer, QuizItem, Quiz}

// Export quiz interface
export type { IQuiz, IQuizItem }
