import mongoose, {Schema, Document} from "mongoose"

// Quiz:
interface IAnswer extends Document {
    // Unique ID auto-generated by DB
    content: string
}

interface IQuizItem extends Document {
    // Unique ID auto-generated by DB
    question: string,
    answers: IAnswer[],
    correctAnswerContent: string
}

interface IQuiz extends Document {
    // Unique ID auto-generated by DB
    name: string, // Quiz name
    quizItems: IQuizItem[] // Questions/Answers
}

const answerSchema = new Schema<IAnswer>({
    content: {
        type: String,
        required: true
    }
})

const quizItemSchema = new Schema<IQuizItem>({
    question: {
        type: String,
        required: true
    },
    answers: {
        type: [answerSchema],
        required: true
    },
    correctAnswerContent: { // Used content instead of id
        type: String,
        required: true
    }
})

const quizSchema = new Schema<IQuiz>({
    name: {
        type: String,
        required: true
    },
    quizItems: {
        type: [quizItemSchema],
        required: true
    }
})

// User:
interface IUser extends Document {
    // Unique ID auto-generated by DB
    email: string,
    password: string,
    quizzes: IQuiz[]
    // Additional attributes as needed...
}

const userSchema = new Schema<IUser>({
    email: {
        type: String,
        required: true,
        unique: true // Prevent duplicate emails
    },
    password: {
        type: String,
        required: true
    },
    quizzes: {
        type: [quizSchema]
    }
})

// Construct the models and export them
const Answer = mongoose.models.Answer ?? mongoose.model("Answer", answerSchema)
const QuizItem = mongoose.models.QuizItem ?? mongoose.model("QuizItem", quizItemSchema)
const Quiz = mongoose.models.Quiz ?? mongoose.model("Quiz", quizSchema)
const User = mongoose.models.User ?? mongoose.model("User", userSchema)

export { User, Answer, QuizItem, Quiz }